const DATA = {
  DEAFULT_COUNTRY_CODE: '86',
  DEAFULT_COUNT_DOWN_NUM : '60',
  DEFAULT_GET_PHONE_VALIDATION_LABEL_ : "获取验证码",
  DEFAULT_REGET_PHONE_VALIDATION_LABEL : "再次获取验证码",
}
module.exports = {
  DATA: DATA
}
